import Head from 'next/head'
import Image from 'next/image'

import { gql, useQuery } from '@apollo/client'
import {useCallback, useEffect} from "react";
import {useBottomScrollListener} from "react-bottom-scroll-listener";

const GetListings = gql`
  query GetListing($first: Int, $after: String) {
    listings(first: $first, after: $after) {
      pageInfo {
        endCursor
        hasNextPage
      }
      edges {
        cursor
        node {
          id
          images {
            picture_url
          }
        }
      }
  }
}

`

export default function Home() {
  const {data, loading, error, fetchMore} = useQuery(GetListings, {
    variables: {first: 20}
  })

  const { endCursor, hasNextPage } = data?.listings.pageInfo || {}

  const handleOnDocumentBottom = useCallback(() => {
    console.log('I am at bottom! ' + Math.round(performance.now()));

    if(hasNextPage) {
      fetchMore({
        variables: {after: endCursor},
        updateQuery: (prevResult, {fetchMoreResult}) => {
          fetchMoreResult.listings.edges = [
            ...prevResult.listings.edges,
            ...fetchMoreResult.listings.edges,
          ];
          return fetchMoreResult;
        },
      });
    }
  }, [endCursor, fetchMore, hasNextPage]);

  useBottomScrollListener(handleOnDocumentBottom);

  if (loading) return <p>Loading...</p>
  if (error) return <p>Oh no... {error.message}</p>
  if (data) { console.log(data) }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={'grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4 p-4'}>
        {data?.listings.edges.map((listing) =>
          <div key={listing.node.id} className={''}>
            <Image className={'aspect-square rounded-md w-full h-full object-cover'} src={listing.node.images.picture_url} width={500} height={500} alt={''}/>
          </div>
        )}
      </div>
    </div>
  )
}